### ISSUE TITLE
throw new Error('Data (' + ipType + ') has not been loaded.')

### ISSUE THREAD

**Issue by gameguardadmin** [chill117/proxy-lists#76] opened 2018-06-27 06:27 UTC
`D:\NewProject>proxy-lists getProxies --stdout
Error: Missing required option (`option.bitproxies.apiKey`): You can get an API key for this service by creating an account at https://bitproxies.eu/
Error: Missing required option (`option.kingproxies.apiKey`): You can get an API key for this service by creating an account at https://kingproxies.com/register
C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\geoip-native-lite\index.js:33
                        throw new Error('Data (' + ipType + ') has not been loaded.');
                        ^

Error: Data (ipv6) has not been loaded.
    at Object.lookup (C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\geoip-native-lite\index.js:33:10)
    at C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\index.js:180:38
    at Function._.map._.collect (C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\underscore\underscore.js:172:24)
    at EventEmitter.<anonymous> (C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\index.js:178:17)
    at EventEmitter.emit (events.js:182:13)
    at C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\sources\freeproxylist.js:36:14
    at C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\async\dist\async.js:2556:16
    at C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\async\dist\async.js:421:16
    at C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\async\dist\async.js:2494:9
    at C:\Users\!\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\async\dist\async.js:421:16
`

**Comment by chill117** [comment] 2018-06-27 12:22
Closing this issue because it is a duplicate of #75 

Some other users have posted a temporary solution there which could work for you as well.

**Closed by chill117** 2018-06-27 12:22 UTC
